# Generated by NEXUS AI Coder
# Task: Implement a prototype of the backend architecture using a suitable programming language and framework

from flask import Flask, jsonify, request

app = Flask(__name__)

# Hardcoded data for demonstration purposes
users = [
    {"id": 1, "name": "John Doe", "email": "john@example.com"},
    {"id": 2, "name": "Jane Doe", "email": "jane@example.com"}
]

# Define a route for the root URL
@app.route("/", methods=["GET"])
def home():
    return "Backend Architecture Prototype"

# Define a route to get all users
@app.route("/users", methods=["GET"])
def get_users():
    return jsonify(users)

# Define a route to get a user by ID
@app.route("/users/<int:user_id>", methods=["GET"])
def get_user(user_id):
    user = next((user for user in users if user["id"] == user_id), None)
    if user is None:
        return jsonify({"message": "User not found"}), 404
    return jsonify(user)

# Define a route to create a new user
@app.route("/users", methods=["POST"])
def create_user():
    new_user = {
        "id": len(users) + 1,
        "name": request.json["name"],
        "email": request.json["email"]
    }
    users.append(new_user)
    return jsonify(new_user), 201

# Define a route to update an existing user
@app.route("/users/<int:user_id>", methods=["PUT"])
def update_user(user_id):
    user = next((user for user in users if user["id"] == user_id), None)
    if user is None:
        return jsonify({"message": "User not found"}), 404
    user["name"] = request.json.get("name", user["name"])
    user["email"] = request.json.get("email", user["email"])
    return jsonify(user)

# Define a route to delete a user
@app.route("/users/<int:user_id>", methods=["DELETE"])
def delete_user(user_id):
    user = next((user for user in users if user["id"] == user_id), None)
    if user is None:
        return jsonify({"message": "User not found"}), 404
    users.remove(user)
    return jsonify({"message": "User deleted"})

if __name__ == "__main__":
    app.run(debug=True)
    print("Backend Architecture Prototype running on http://localhost:5000")