# Generated by NEXUS AI Coder
# Task: Sort products by revenue

# Define a list of products with their prices and quantities sold
products = [
    {"name": "Product A", "price": 10.99, "quantity": 100},
    {"name": "Product B", "price": 5.99, "quantity": 200},
    {"name": "Product C", "price": 7.99, "quantity": 50},
    {"name": "Product D", "price": 12.99, "quantity": 150},
    {"name": "Product E", "price": 8.99, "quantity": 300}
]

# Calculate the revenue for each product
for product in products:
    product["revenue"] = product["price"] * product["quantity"]

# Sort the products by revenue in descending order
products.sort(key=lambda x: x["revenue"], reverse=True)

# Print the sorted products
for product in products:
    print(f"Name: {product['name']}, Revenue: {product['revenue']}")