import os
import re
import sys
import autogen

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))

from nexus_ai.config import get_llm_config, NEXUS_CONFIG
from nexus_ai.utils.logger import NexusLogger

from tools.code_executor import run_code_agent, execute_python_code


OUTPUT_CODE_DIR = os.getenv("CODE_OUTPUT_DIR", "data/generated_code")


def _slugify(text: str) -> str:
    text = text.lower().strip()
    text = re.sub(r"[^a-z0-9\s_]", "", text)
    text = re.sub(r"\s+", "_", text)
    return text[:50]


def _save_code_and_docs(task: str, code: str, output: str, explanation: str) -> dict:
    os.makedirs(OUTPUT_CODE_DIR, exist_ok=True)
    slug = _slugify(task)

    py_path = os.path.join(OUTPUT_CODE_DIR, f"{slug}.py")
    md_path = os.path.join(OUTPUT_CODE_DIR, f"{slug}.md")

    with open(py_path, "w", encoding="utf-8") as f:
        f.write(f"# Generated by NEXUS AI Coder\n# Task: {task}\n\n")
        f.write(code)

    with open(md_path, "w", encoding="utf-8") as f:
        f.write(f"# {task.title()}\n\n")
        f.write(f"**Generated by NEXUS AI Coder**\n\n")
        f.write(f"## Task\n{task}\n\n")
        f.write(f"## Code\n```python\n{code}\n```\n\n")
        f.write(f"## Execution Output\n```\n{output}\n```\n\n")
        f.write(f"## Explanation\n{explanation}\n")

    abs_py = os.path.abspath(py_path)
    abs_md = os.path.abspath(md_path)
    print(f"\n  [Coder] ✔ Code saved  → {abs_py}")
    print(f"  [Coder] ✔ Docs saved  → {abs_md}\n")

    return {"py_path": abs_py, "md_path": abs_md}


def get_coder_agent():
    return autogen.AssistantAgent(
        name="CoderAgent",
        system_message="""You are a Coder Agent inside NEXUS AI.

Your ONLY job is to write and execute Python code — but ONLY when the task genuinely requires it.

A task requires code when:
- The user explicitly asks for a script, program, function, or algorithm
- The task involves computation, data processing, automation, or file generation
- The output must be executable

A task does NOT require code when:
- The output is written content (text, plans, reports, analysis, explanations)
- No computation or execution is needed to produce the answer

If code IS needed:
- Write clean, self-contained, executable Python
- Hardcode all values — never use input() or sys.stdin
- Output ONLY the code block, then [CODE READY]

```python
# code here
```
[CODE READY]

If code is NOT needed, output exactly: NO_CODE_NEEDED""",
        llm_config=get_llm_config(temperature=0.2, max_tokens=1024),
        max_consecutive_auto_reply=3,
        human_input_mode="NEVER",
    )


def get_explainer_agent():
    return autogen.AssistantAgent(
        name="CodeExplainerAgent",
        system_message="""You are a Code Explainer inside NEXUS AI.
Given Python code and its output, write a clear markdown explanation:
1. What the code does (2-3 sentences)
2. How it works (step-by-step, brief)
3. Key concepts used
4. Sample output interpretation
Be concise and educational. Always end with: [EXPLANATION COMPLETE]""",
        llm_config=get_llm_config(temperature=0.4),
        max_consecutive_auto_reply=3,
        human_input_mode="NEVER",
    )


def run_coder(user_query: str, plan: dict, session: str = "default") -> dict:
    logger = NexusLogger(session)

    needs_code = plan.get("needs_code", False)

    coder_tasks = [
        t["description"] for t in plan.get("tasks", [])
        if t.get("agent") == "Coder"
    ]

    # Only proceed if plan explicitly flagged code OR there are Coder-assigned tasks
    if not needs_code and not coder_tasks:
        logger.log("CODER", "SKIP", "No code tasks in plan")
        return {"skipped": True, "reason": "No code tasks in plan", "code": "", "output": ""}

    task_description = coder_tasks[0] if coder_tasks else user_query

    logger.log("CODER", "START", task_description[:100])
    result = run_code_agent(task_description)

    code   = result.get("code", "")
    output = result.get("output", "")

    if not code or "NO_CODE_NEEDED" in code:
        logger.log("CODER", "NO_CODE", "Agent determined no code needed")
        return {"skipped": True, "reason": "No code produced", "code": "", "output": ""}

    explainer = get_explainer_agent()
    proxy = autogen.UserProxyAgent(
        name="ExplainerProxy",
        human_input_mode="NEVER",
        max_consecutive_auto_reply=1,
        code_execution_config=False,
    )
    chat = proxy.initiate_chat(
        recipient=explainer,
        message=(
            f"Task: {task_description}\n\n"
            f"Code:\n```python\n{code}\n```\n\n"
            f"Output:\n{output}\n\n"
            "Write the explanation."
        ),
        max_turns=1,
    )
    explanation = ""
    for msg in chat.chat_history:
        if msg.get("role") == "assistant" or msg.get("name") == "CodeExplainerAgent":
            explanation = msg.get("content", "")

    paths = _save_code_and_docs(task_description, code, output, explanation)

    logger.log("CODER", "DONE", f"py={paths['py_path']}")
    return {
        "skipped":     False,
        "task":        task_description,
        "code":        code,
        "output":      output,
        "explanation": explanation,
        "py_path":     paths["py_path"],
        "md_path":     paths["md_path"],
    }