services:
  mongo:
    image: mongo:6
    container_name: mongo
    volumes:
    - mongo-data:/data/db

  server1:
    build: ./server
    container_name: node-server-1
    depends_on:
      - mongo
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app

  server2:
    build: ./server
    container_name: node-server-2
    depends_on:
      - mongo
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app

  client:
    build: ./client
    container_name: react-client
    ports:
      - "3000:3000"
    depends_on:
      - server1
      - server2
    volumes:
      - ./client:/app

  # Day 3 
  # nginx:
  #   image: nginx:latest
  #   container_name: nginx-proxy
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - server1
  #     - server2

  # Day 4
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - server1
      - server2
volumes:
  mongo-data: