# day 5 - final
events {}

http {

    upstream backend_servers {
        server server1:5000;
        server server2:5000;
    }

    upstream frontend {
        server client:3000;
    }

    # HTTP → HTTPS redirect
    server {
        listen 80;
        server_name docker.local;

        return 301 https://$host$request_uri;
    }

    # HTTPS server
    server {
        listen 443 ssl;
        server_name docker.local;

        ssl_certificate /etc/nginx/certs/docker.local.pem;
        ssl_certificate_key /etc/nginx/certs/docker.local-key.pem;

        ssl_protocols TLSv1.2 TLSv1.3;

        # React frontend
        location / {
            proxy_pass http://frontend/;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Backend API
        location /api {
            proxy_pass http://backend_servers;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}