import subprocess
import tempfile
import os
import re
import autogen
from dotenv import load_dotenv

load_dotenv()

FILES_DIR = os.getenv("FILES_DIR", "data/files")


def ensure_files_dir():
    os.makedirs(FILES_DIR, exist_ok=True)


def save_code_to_file(code: str, task_description: str, task_id: str = "") -> str:
    ensure_files_dir()

    # Build a safe filename from task_id or a slug of the description
    if task_id:
        slug = re.sub(r"[^a-z0-9_]", "_", task_id.lower())
    else:
        slug = re.sub(r"[^a-z0-9_]", "_", task_description[:40].lower())
        slug = re.sub(r"_+", "_", slug).strip("_")

    filename = f"generated_{slug}.py"
    path = os.path.join(FILES_DIR, filename)

    header = f"# Auto-generated by CodeAgent\n# Task: {task_description}\n\n"
    with open(path, "w", encoding="utf-8") as f:
        f.write(header + code)

    print(f"[CodeAgent] Code saved → {path}")
    return path


def execute_python_code(code: str) -> str:
    with tempfile.NamedTemporaryFile(mode="w", suffix=".py", delete=False) as f:
        f.write(code)
        tmp_path = f.name

    try:
        result = subprocess.run(
            ["python", tmp_path],
            capture_output=True,
            text=True,
            timeout=15,
        )
        output = result.stdout.strip() if result.stdout else result.stderr.strip()
        return output or "[No output produced]"
    except subprocess.TimeoutExpired:
        return "[ERROR] Code execution timed out (15s limit)"
    except Exception as e:
        return f"[ERROR] Execution failed: {str(e)}"
    finally:
        os.unlink(tmp_path)


def get_code_agent():
    config_list = [
        {
            "model": os.getenv("MODEL_NAME", "phi3"),
            "base_url": os.getenv("OPENAI_API_BASE", "http://localhost:11434/v1"),
            "api_key": os.getenv("OPENAI_API_KEY", "ollama"),
        }
    ]

    llm_config = {
        "config_list": config_list,
        "temperature": 0.3,
        "max_tokens": 768,
    }

    code_agent = autogen.AssistantAgent(
        name="CodeAgent",
        system_message="""You are a Code Execution Agent. Your ONLY job is:
- Receive a task that requires Python code to solve
- Write clean, correct Python code to solve it
- Output the code in this EXACT format (no extra text before or after):

```python
# your code here
```

- After the code block, write: [CODE READY FOR EXECUTION]
- The code must be self-contained (import what it needs, print() the final result)
- CRITICAL: NEVER use input(), sys.stdin, or any interactive functions — hardcode all values directly
- CRITICAL: Always hardcode the specific values mentioned in the task (e.g. principal=10000, rate=8, time=5)
- CRITICAL: End with a print() statement showing the final result
- Do NOT explain the code, just write it
Stay strictly in your lane: write executable Python only.""",
        llm_config=llm_config,
        max_consecutive_auto_reply=5,
        human_input_mode="NEVER",
    )

    return code_agent


def run_code_agent(task_description: str, task_id: str = "") -> dict:
    """
    Asks the Code Agent to write code, executes it, and saves it to a .py file.
    Returns {"task": ..., "code": ..., "output": ..., "code_file": ...}
    """
    agent = get_code_agent()

    user_proxy = autogen.UserProxyAgent(
        name="CodeProxy",
        human_input_mode="NEVER",
        max_consecutive_auto_reply=1,
        code_execution_config=False,
    )

    chat_result = user_proxy.initiate_chat(
        recipient=agent,
        message=f"Write Python code to solve this task:\n\n{task_description}",
        max_turns=1,
    )

    raw = ""
    for msg in chat_result.chat_history:
        if msg.get("role") == "assistant" or msg.get("name") == "CodeAgent":
            raw = msg.get("content", "")

    # Extract code block
    code_match = re.search(r"```python\n(.*?)```", raw, re.DOTALL)
    code = code_match.group(1).strip() if code_match else ""

    if not code:
        return {
            "task": task_description,
            "code": "",
            "output": "[ERROR] No code block found in agent response.",
            "code_file": None,
        }

    # Strip any accidental tags inside the code block
    code = code.replace("[CODE READY FOR EXECUTION]", "").strip()

    # Save code to file
    code_file = save_code_to_file(code, task_description, task_id)

    print(f"[CodeAgent] Extracted code ({len(code)} chars). Executing...")
    output = execute_python_code(code)
    print(f"[CodeAgent] Execution output: {output[:200]}")

    return {"task": task_description, "code": code, "output": output, "code_file": code_file}